name: Deploy node application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t ajaysonere/trade-web-client .
      - name: Publish image to docker hub
        run: docker push ajaysonere/trade-web-client:latest

  deploy:
     needs: build
     runs-on: self-hosted
     steps:
       - name: Give the permission to docker hub
         run: sudo chmod 666 /var/run/docker.sock
       - name: Pull image from docker hub
         run: docker pull ajaysonere/trade-web-client
       - name: Delete the previous container
         run: docker rm -f trade-client
       - name: Run the docker image
         run: docker run -d -p 80:80 --name trade-client ajaysonere/trade-web-client:latest
         